stages:
  - run

run-notebook-in-development-environment:
  stage: run
  image: python:3.8
  tags: [ 'self-hosted' ]
  before_script:
    - echo "Installing Jupyter"
    - python -m pip install --upgrade pip
    - pip install jupyter
    - echo "Executing Jupyter notebook"
  script:
    - jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb
  artifacts:
    when: always
    paths:
      - notebooks/demo-pipeline.ipynb
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes: [ "notebooks/**" ]

run-files-in-development-environment:
  stage: run
  image: python:3.8
  tags: [ 'self-hosted' ]
  before_script:
    - echo "Installing Python deps"
    - python -m pip install --upgrade pip
    - pip install pandas numpy 'kfp~=1.8.14' scikit-learn
    - echo "Executing Python files"
  script:
    - python src/submit_run.py
  artifacts:
    when: always
    paths:
      - run.log
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes: [ "src/**" ]
